<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=0.3">
    <!-- 最新 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- 可选的Bootstrap主题文件（一般不用引入） -->
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/docs.css">

    <link rel="shortcut icon" href="favicon.ico" />
    <script src="/js/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <title>同行者借阅书籍列表</title>
</head>
<body>
<div class="container content">
    <div class="row" style="margin-top:40px;">
        <div class="col-md-12">
            <style>
                .form-div{display:inline-block; min-width:400px;margin-bottom:15px;}
                .form-div label{width:100px;}
            </style>
            <form class="form-inline" role="form" action = "" method = "POST">
                <div class="form-div">
                    <label>书籍编号：</label>
                    <input type="text" name="id" value="<?php if(!empty($params['id'])){ echo $params['id']; } ?>"/>
                </div>
                <div class="form-div" >
                    <label>书名：</label>
                    <input type="text"  name="title" value="<?php if(!empty($params['title'])){ echo $params['title']; } ?>"/>
                </div>
                <br/>
                <div class="form-div" >
                    <label>类型：</label>
                    <select name="type">
                        <option value="0" <?php if(!isset($params['type']) || $params['type'] == '0' ){ echo "selected"; } ?>><?php echo '全部';?></option>
                        <?php foreach($type as $k=>$v){ ?>
                            <option value="<?php echo $k;?>" <?php if(isset($params['type']) && $params['type'] == $k ){ echo "selected"; } ?>><?php echo $v;?></option>
                        <?php } ?>
                    </select>
                </div>
                <br/>
                <div class="form-div" >
                    <label>书籍分类：</label>
                    <select name="category">
                        <option value="0" <?php if(!isset($params['category']) || $params['category'] == '' ){ echo "selected"; } ?>><?php echo '全部';?></option>
                        <?php foreach($category as $v){ ?>
                            <option value="<?php echo $v;?>" <?php if(isset($params['category']) && $params['category'] == $v ){ echo "selected"; } ?>><?php echo $v;?></option>
                        <?php } ?>
                    </select>
                </div>
                <br>
                <div class="form-div" >
                    <label>状态：</label>
                    <input type="radio"  name="status" value="" <?php if(empty($params['status'])){ echo 'checked';} ?>/> 全部
                    <input type="radio"  name="status" value="1" <?php if(!empty($params['status']) && $params['status']=='1'){ echo 'checked'; } ?>/> 可借阅
                    <input type="radio"  name="status" value="2" <?php if(!empty($params['status']) && $params['status']=='2'){ echo 'checked'; } ?>/> 已下架
                    <input type="radio"  name="status" value="3" <?php if(!empty($params['status']) && $params['status']=='3'){ echo 'checked'; } ?>/> 已借出
                </div>
                <br/>
                <button type="submit" class="btn btn-default">搜索</button>
                <br/><br/>
            </form>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="app-panel-title" >书籍列表</span>
                    <div style="clear:both;"></div>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered table-striped">
                        <tr><td>书籍编号</td><td>类型</td><td>书名</td><td>书籍分类</td><td>作者</td><td>出版社</td><td>版本</td><td>状态</td></tr>
                        <?php foreach($show_list as $val){ ?>
                        <tr>
                            <td><?php echo $val['id'];?></td>
                            <td><?php echo $type[$val['type']];?></td>
                            <td><?php echo $val['title'];?></td>
                            <td><?php echo $val['category'];?></td>
                            <td><?php echo $val['author'];?></td>
                            <td><?php echo $val['press'];?></td>
                            <td><?php echo $val['version'];?></td>
                            <td><?php if($val['status']==1){echo '可借阅';}elseif($val['status']==2){echo '已下架';}else{echo '已借出';};?></td>
                        </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <p class="text-center text-muted copyright"> 安徽同行者教育咨询有限公司</p>
    </div>
</div>
</body>
</html>
